// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParkingHub.Data;

#nullable disable

namespace ParkingHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParkingHub.Data.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ParkingHub.Data.Entities.CompanyParkQuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSpots")
                        .HasColumnType("integer");

                    b.Property<int>("OccupiedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ParkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ParkId");

                    b.ToTable("CompanyParkQuotas");
                });

            modelBuilder.Entity("ParkingHub.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentParkId")
                        .HasColumnType("integer");

                    b.Property<bool>("InsidePark")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ParkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CurrentParkId");

                    b.HasIndex("ParkId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ParkingHub.Data.Entities.LicensePlate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LicensePlates");
                });

            modelBuilder.Entity("ParkingHub.Data.Entities.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OccupiedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Parks");
                });

            modelBuilder.Entity("ParkingHub.Data.Entities.CompanyParkQuota", b =>
                {
                    b.HasOne("ParkingHub.Data.Entities.Company", "Company")
                        .WithMany("CompanyParkQuotas")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingHub.Data.Entities.Park", "Park")
                        .WithMany("CompanyParkQuotas")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Park");
                });

            modelBuilder.Entity("ParkingHub.Data.Entities.Employee", b =>
                {
                    b.HasOne("ParkingHub.Data.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingHub.Data.Entities.Park", "CurrentPark")
                        .WithMany()
                        .HasForeignKey("CurrentParkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ParkingHub.Data.Entities.Park", null)
                        .WithMany("Employees")
                        .HasForeignKey("ParkId");

                    b.Navigation("Company");

                    b.Navigation("CurrentPark");
                });

            modelBuilder.Entity("ParkingHub.Data.Entities.LicensePlate", b =>
                {
                    b.HasOne("ParkingHub.Data.Entities.Employee", "Employee")
                        .WithMany("LicensePlates")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ParkingHub.Data.Entities.Company", b =>
                {
                    b.Navigation("CompanyParkQuotas");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ParkingHub.Data.Entities.Employee", b =>
                {
                    b.Navigation("LicensePlates");
                });

            modelBuilder.Entity("ParkingHub.Data.Entities.Park", b =>
                {
                    b.Navigation("CompanyParkQuotas");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
